In [1]:
!pip install pandasql
import pandas as pd
import numpy as np
from pandasql import PandaSQL
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

Requirement already satisfied: pandasql in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.7.3)
Requirement already satisfied: numpy in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandasql) (2.5.3)
Requirement already satisfied: pandas in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandasql) (3.0.5)
Requirement already satisfied: sqlalchemy in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandasql) (2.0.54)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->pandasql) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Requirement already satisfied: greenlet>=1 in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy->pandasql) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\umed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy->pandasql) (4.16.0)

In [6]:
# Онлайн 


# 1. НАСТРОЙКИ

n = 25
date = pd.date_range(start='2026-01-30', periods=n, freq='D')


# 2. ДАННЫЕ (befor и after для каждой глубины)

data = {
    'date': date,
    
  
    # ГЛУБИНА 1 (fpd_01)
    
    'fpd_01_befor': np.random.randint(1, 200, n),
    'cum_debt_01_befor': np.random.randint(300, 700, n),
    'fpd_01_after': np.random.randint(1, 200, n),
    'cum_debt_01_after': np.random.randint(300, 700, n),
    
    
    # ГЛУБИНА 2 (fpd_05)
    
    'fpd_05_befor': np.random.randint(10, 100, n),
    'cum_debt_02_befor': np.random.randint(200, 500, n),
    'fpd_05_after': np.random.randint(10, 100, n),
    'cum_debt_02_after': np.random.randint(200, 500, n),
    
    
    # ГЛУБИНА 3 (fpd_07)
    
    'fpd_07_befor': np.random.randint(0, 20, n),
    'cum_debt_03_befor': np.random.randint(50, 200, n),
    'fpd_07_after': np.random.randint(0, 20, n),
    'cum_debt_03_after': np.random.randint(50, 200, n),
}


# 3. СОЗДАЁМ DATAFRAME

df = pd.DataFrame(data)
df

,date,fpd_01_befor,cum_debt_01_befor,fpd_01_after,cum_debt_01_after,fpd_05_befor,cum_debt_02_befor,fpd_05_after,cum_debt_02_after,fpd_07_befor,cum_debt_03_befor,fpd_07_after,cum_debt_03_after
0,2026-01-30,10,454,165,367,39,453,10,491,8,163,13,83
1,2026-01-31,38,463,199,308,74,277,44,266,4,139,16,194
2,2026-02-01,137,325,65,346,66,329,34,324,13,81,7,177
3,2026-02-02,86,392,46,497,81,465,46,368,13,79,2,83
4,2026-02-03,108,663,142,448,21,241,67,345,2,56,0,125
5,2026-02-04,119,639,39,536,21,208,20,302,13,156,19,74
6,2026-02-05,84,653,79,399,76,292,49,495,11,82,10,58
7,2026-02-06,175,381,64,634,32,340,99,464,1,87,9,102
8,2026-02-07,180,408,44,585,14,394,69,319,6,159,3,116
9,2026-02-08,197,372,67,579,35,368,67,369,19,195,3,108
10,2026-02-09,186,553,71,574,42,448,69,498,4,54,2,178
11,2026-02-10,22,653,47,394,69,435,74,393,8,97,19,90
12,2026-02-11,51,674,140,565,41,423,84,440,12,113,1,120
13,2026-02-12,93,590,88,415,27,473,47,240,12,137,7,144
14,2026-02-13,39,610,100,602,99,290,83,257,17,87,8,194
15,2026-02-14,167,569,144,543,16,329,77,339,17,83,9,195
16,2026-02-15,133,495,85,672,87,330,87,267,0,139,8,83
17,2026-02-16,116,375,55,331,55,331,57,309,13,138,12,77
18,2026-02-17,66,312,161,335,68,374,60,426,0,150,8,103
19,2026-02-18,113,539,196,358,33,405,17,390,8,51,17,65
20,2026-02-19,19,398,52,617,76,284,19,233,16,194,0,171
21,2026-02-20,113,422,50,342,99,261,50,318,11,72,1,70
22,2026-02-21,170,309,32,643,44,374,44,263,0,88,1,57
23,2026-02-22,1,566,75,410,56,340,12,468,0,137,3,87
24,2026-02-23,168,578,192,556,50,422,92,356,14,102,4,53

In [3]:

# СПИСОК ПАР (fpd, cum_debt, delta)

pairs = [
    ('fpd_01_befor', 'cum_debt_01_befor', 'delta_01_befor'),
    ('fpd_01_after', 'cum_debt_01_after', 'delta_01_after'),
    ('fpd_05_befor', 'cum_debt_02_befor', 'delta_05_befor'),
    ('fpd_05_after', 'cum_debt_02_after', 'delta_05_after'),
    ('fpd_07_befor', 'cum_debt_03_befor', 'delta_07_befor'),
    ('fpd_07_after', 'cum_debt_03_after', 'delta_07_after'),
]


# ЦИКЛ ПО ПАРАМ

for fpd_col, debt_col, delta_col in pairs:
    df[delta_col] = df[fpd_col].cumsum() / df[debt_col].cumsum()

df

,date,fpd_01_befor,cum_debt_01_befor,fpd_01_after,cum_debt_01_after,fpd_05_befor,cum_debt_02_befor,fpd_05_after,cum_debt_02_after,fpd_07_befor,cum_debt_03_befor,fpd_07_after,cum_debt_03_after,delta_01_befor,delta_01_after,delta_05_befor,delta_05_after,delta_07_befor,delta_07_after
0,2026-01-30,45,343,16,697,21,485,10,398,4,126,3,192,0.131195,0.022956,0.043299,0.025126,0.031746,0.015625
1,2026-01-31,113,440,96,676,90,479,33,440,9,94,17,132,0.201788,0.081573,0.115145,0.051313,0.059091,0.061728
2,2026-02-01,97,471,30,381,82,237,32,459,6,188,1,101,0.203349,0.080958,0.160699,0.057826,0.046569,0.049412
3,2026-02-02,98,691,197,476,23,260,46,219,1,99,19,51,0.181491,0.152018,0.147844,0.079815,0.039448,0.084034
4,2026-02-03,38,425,7,489,67,463,27,292,7,78,16,196,0.164979,0.127253,0.147089,0.081858,0.046154,0.083333
5,2026-02-04,160,499,111,435,32,295,96,388,7,121,7,93,0.192053,0.144895,0.141956,0.111111,0.048159,0.082353
6,2026-02-05,173,693,184,499,63,326,89,391,6,171,8,53,0.203257,0.175472,0.148527,0.128721,0.045610,0.086797
7,2026-02-06,72,444,14,502,97,450,16,442,12,149,3,172,0.198702,0.157641,0.158598,0.115220,0.050682,0.074747
8,2026-02-07,155,651,91,369,78,481,21,498,12,151,13,142,0.204209,0.164898,0.159091,0.104905,0.054376,0.076855
9,2026-02-08,41,596,58,398,60,468,41,357,15,118,17,134,0.188844,0.163348,0.155426,0.105819,0.061004,0.082148
10,2026-02-09,90,457,148,395,44,428,42,477,8,164,7,68,0.189492,0.179048,0.150274,0.103875,0.059630,0.083208
11,2026-02-10,10,672,159,603,11,355,13,336,10,159,11,132,0.171106,0.187669,0.141316,0.099212,0.059951,0.083220
12,2026-02-11,128,343,6,326,10,266,70,306,16,135,5,75,0.181413,0.178834,0.135790,0.107136,0.064461,0.082414
13,2026-02-12,47,530,184,509,50,292,41,340,1,117,13,58,0.174638,0.192598,0.137748,0.107992,0.060963,0.087555
14,2026-02-13,82,327,6,537,14,278,48,313,4,167,14,126,0.177921,0.179238,0.133381,0.110502,0.057928,0.089275
15,2026-02-14,55,526,77,418,40,203,39,251,16,69,3,75,0.173162,0.179507,0.135623,0.112409,0.063628,0.087222
16,2026-02-15,100,578,17,524,70,486,90,360,8,60,16,55,0.173152,0.170148,0.136276,0.120313,0.065559,0.093261
17,2026-02-16,27,513,169,504,71,332,12,208,9,171,5,198,0.166431,0.179675,0.140188,0.118301,0.064613,0.086702
18,2026-02-17,150,314,57,561,31,296,95,489,0,164,4,148,0.176706,0.174965,0.138663,0.123636,0.060376,0.082690
19,2026-02-18,127,481,177,474,58,368,74,439,17,196,15,183,0.180909,0.184590,0.139625,0.126300,0.062291,0.082634
20,2026-02-19,197,605,140,538,80,387,19,441,18,155,16,149,0.189169,0.188537,0.143026,0.121622,0.065217,0.084090
21,2026-02-20,42,653,169,581,15,326,66,407,19,79,1,126,0.181923,0.193996,0.139053,0.123621,0.069942,0.080481
22,2026-02-21,11,617,194,682,60,497,48,293,18,177,10,185,0.173393,0.199326,0.137976,0.125000,0.071750,0.078762
23,2026-02-22,131,662,56,486,40,319,70,428,19,152,3,177,0.174687,0.195937,0.137519,0.126839,0.074233,0.075141
24,2026-02-23,114,529,80,397,25,301,56,242,7,90,15,80,0.176340,0.196115,0.135713,0.129585,0.074328,0.078039

In [4]:

# НАЧИНАЕМ С КОЛОНКИ DATE

# Новый DataFrame пока что только с колонкой date
result = pd.DataFrame({'date': df['date']})


# ДОБАВЛЯЕМ ВСЕ DELTA-КОЛОНКИ ЧЕРЕЗ ЦИКЛ

# Создаём массив (одномерный) из новых колонок delta 
delta_cols = [
    'delta_01_befor',
    'delta_01_after',
    'delta_05_befor',
    'delta_05_after',
    'delta_07_befor',
    'delta_07_after',
]

# Цикл передач колонок в dataframe = result
for col in delta_cols:
    result[col] = df[col]

# таблица delt
result

,date,delta_01_befor,delta_01_after,delta_05_befor,delta_05_after,delta_07_befor,delta_07_after
0,2026-01-30,0.131195,0.022956,0.043299,0.025126,0.031746,0.015625
1,2026-01-31,0.201788,0.081573,0.115145,0.051313,0.059091,0.061728
2,2026-02-01,0.203349,0.080958,0.160699,0.057826,0.046569,0.049412
3,2026-02-02,0.181491,0.152018,0.147844,0.079815,0.039448,0.084034
4,2026-02-03,0.164979,0.127253,0.147089,0.081858,0.046154,0.083333
5,2026-02-04,0.192053,0.144895,0.141956,0.111111,0.048159,0.082353
6,2026-02-05,0.203257,0.175472,0.148527,0.128721,0.045610,0.086797
7,2026-02-06,0.198702,0.157641,0.158598,0.115220,0.050682,0.074747
8,2026-02-07,0.204209,0.164898,0.159091,0.104905,0.054376,0.076855
9,2026-02-08,0.188844,0.163348,0.155426,0.105819,0.061004,0.082148
10,2026-02-09,0.189492,0.179048,0.150274,0.103875,0.059630,0.083208
11,2026-02-10,0.171106,0.187669,0.141316,0.099212,0.059951,0.083220
12,2026-02-11,0.181413,0.178834,0.135790,0.107136,0.064461,0.082414
13,2026-02-12,0.174638,0.192598,0.137748,0.107992,0.060963,0.087555
14,2026-02-13,0.177921,0.179238,0.133381,0.110502,0.057928,0.089275
15,2026-02-14,0.173162,0.179507,0.135623,0.112409,0.063628,0.087222
16,2026-02-15,0.173152,0.170148,0.136276,0.120313,0.065559,0.093261
17,2026-02-16,0.166431,0.179675,0.140188,0.118301,0.064613,0.086702
18,2026-02-17,0.176706,0.174965,0.138663,0.123636,0.060376,0.082690
19,2026-02-18,0.180909,0.184590,0.139625,0.126300,0.062291,0.082634
20,2026-02-19,0.189169,0.188537,0.143026,0.121622,0.065217,0.084090
21,2026-02-20,0.181923,0.193996,0.139053,0.123621,0.069942,0.080481
22,2026-02-21,0.173393,0.199326,0.137976,0.125000,0.071750,0.078762
23,2026-02-22,0.174687,0.195937,0.137519,0.126839,0.074233,0.075141
24,2026-02-23,0.176340,0.196115,0.135713,0.129585,0.074328,0.078039

In [5]:
тепер ьмне нужно написать цикл который будет считать куьулативную дельту по колонкам 
тоест ьтак 
колонка fpd_01(0)/cum_debt

SyntaxError: invalid syntax (1202790865.py, line 1)

In [ ]:
# Офла 

# 1. НАСТРОЙКИ

n = 25
date = pd.date_range(start='2026-01-30', periods=n, freq='D')


# 2. ДАННЫЕ (befor и after для каждой глубины)

data = {
    'date': date,
    

    # ГЛУБИНА 1 (fpd_01)

    'fpd_01_befor': np.random.randint(1, 200, n),
    'cum_debt_01_befor': np.random.randint(300, 700, n),
    'fpd_01_after': np.random.randint(1, 200, n),
    'cum_debt_01_after': np.random.randint(300, 700, n),
    
    
    # ГЛУБИНА 2 (fpd_05)
   
    'fpd_05_befor': np.random.randint(10, 100, n),
    'cum_debt_02_befor': np.random.randint(200, 500, n),
    'fpd_05_after': np.random.randint(10, 100, n),
    'cum_debt_02_after': np.random.randint(200, 500, n),
    
    
    # ГЛУБИНА 3 (fpd_07)
   
    'fpd_07_befor': np.random.randint(0, 20, n),
    'cum_debt_03_befor': np.random.randint(50, 200, n),
    'fpd_07_after': np.random.randint(0, 20, n),
    'cum_debt_03_after': np.random.randint(50, 200, n),
}


# 3. СОЗДАЁМ DATAFRAME
=
df = pd.DataFrame(data)
df

In [ ]:
# Фильтруем данные
pdsql = PandaSQL()
df2 = pdsql

res = pdsql("""Select * From df WHERE strftime('%w', date) BETWEEN '1' AND '5'""")
res

In [ ]:

# СПИСОК ПАР (fpd, cum_debt, delta)

pairs02 = [
    ('fpd_01_befor', 'cum_debt_01_befor', 'delta_01_befor'),
    ('fpd_01_after', 'cum_debt_01_after', 'delta_01_after'),
    ('fpd_05_befor', 'cum_debt_02_befor', 'delta_05_befor'),
    ('fpd_05_after', 'cum_debt_02_after', 'delta_05_after'),
    ('fpd_07_befor', 'cum_debt_03_befor', 'delta_07_befor'),
    ('fpd_07_after', 'cum_debt_03_after', 'delta_07_after'),
]


# ЦИКЛ ПО ПАРАМ

for fpd_col, debt_col, delta_col in pairs:
    df[delta_col] = df[fpd_col].cumsum() / df[debt_col].cumsum()

res

In [ ]:

# НАЧИНАЕМ С КОЛОНКИ DATE

# Новый DataFrame пока что только с колонкой date
result = pd.DataFrame({'date': res['date']})

# ДОБАВЛЯЕМ ВСЕ DELTA-КОЛОНКИ ЧЕРЕЗ ЦИКЛ

# Создаём массив (одномерный) из новых колонок delta 
delta_cols = [
    'delta_01_befor',
    'delta_01_after',
    'delta_05_befor',
    'delta_05_after',
    'delta_07_befor',
    'delta_07_after',
]

# Цикл передач колонок в dataframe = result
for col in delta_cols:
    result[col] = df[col]

# таблица delt
result

In [ ]:

# ==============================================
# СПИСОК ГРУПП (ТОЛЬКО DELTA)
# ==============================================
#groups = [
#    {
#        'title': 'Группа 1: delta_01',
#        'cols': ['delta_01_befor', 'delta_01_after'],
#    },
#    {
#        'title': 'Группа 2: delta_05',
#        'cols': ['delta_05_befor', 'delta_05_after'],
#    },
#    {
#        'title': 'Группа 3: delta_07',
#        'cols': ['delta_07_befor', 'delta_07_after'],
#    },
#]
#
# ==============================================
# СОЗДАЁМ 3 ГРАФИКА
# ==============================================
#fig, axes = plt.subplots(3, 1, figsize=(14, 15))

#for ax, group in zip(axes, groups):
#    for col in group['cols']:
#        ax.plot(df['date'], df[col], label=col)
#    
#    ax.set_title(group['title'])
#    ax.set_xlabel('Дата')
#    ax.set_ylabel('Delta')
#    ax.legend()
#    ax.grid(True, alpha=0.3)
#    ax.tick_params(axis='x', rotation=45)

#plt.tight_layout()
#plt.show()

In [ ]:
# uHFABR

# ABkmnfwbz 
fig, axes = plt.subplots(3, 1, figsize=(14, 15))


# ГРАФИК 1

axes[0].plot(df['date'], df['delta_01_befor'], label='befor')
axes[0].plot(df['date'], df['delta_01_after'], label='after')
axes[0].set_title('Группа 1: delta_01')
axes[0].legend()
axes[0].yaxis.set_major_formatter(PercentFormatter(1.0))   # ← ЗДЕСЬ!


# ГРАФИК 2

axes[1].plot(df['date'], df['delta_05_befor'], label='befor')
axes[1].plot(df['date'], df['delta_05_after'], label='after')
axes[1].set_title('Группа 2: delta_05')
axes[1].legend()
axes[1].yaxis.set_major_formatter(PercentFormatter(1.0))   # ← ЗДЕСЬ!


# ГРАФИК 3

axes[2].plot(df['date'], df['delta_07_befor'], label='befor')
axes[2].plot(df['date'], df['delta_07_after'], label='after')
axes[2].set_title('Группа 3: delta_07')
axes[2].legend()
axes[2].yaxis.set_major_formatter(PercentFormatter(1.0))   # ← ЗДЕСЬ!

plt.tight_layout()
plt.show()

In [ ]:


fig, ax = plt.subplots(figsize=(14, 6))


# РИСУЕМ ЛИНИИ

ax.plot(df['date'], df['delta_01_befor'] * 100, marker='o', label='befor')
ax.plot(df['date'], df['delta_01_after'] * 100, marker='o', label='after')


# ПОДПИСЫВАЕМ КАЖДУЮ ТОЧКУ

for i, (x, y) in enumerate(zip(df['date'], df['delta_01_befor'] * 100)):
    ax.annotate(f'{y:.1f}%', (x, y), textcoords="offset points", xytext=(0, 10), ha='center', fontsize=8)

ax.set_title('Группа 1: delta_01 (%)')
ax.set_ylabel('Проценты (%)')
ax.legend()
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()